import { createClient } from "@/lib/supabase/server";
import Link from "next/link";

export default async function PublicReportPage({
  params,
}: {
  params: Promise<{ publicId: string }>;
}) {
  const { publicId } = await params;
  const supabase = await createClient();

  const { data: report } = await supabase
    .from("reports")
    .select("*")
    .eq("public_id", publicId)
    .single();

  if (!report) {
    return <div className="p-10 text-white bg-black rounded-xl">Report not found</div>;
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-900 to-slate-900 text-white p-10">
      <div className="max-w-3xl mx-auto rounded-xl border border-white/10 bg-slate-800 p-12 shadow-lg">
        <div className="text-center">
          <h1 className="text-5xl font-bold tracking-tight mb-4">
            {report.title}
          </h1>
          <p className="text-lg text-zinc-300 mb-8">{report.summary}</p>
        </div>

        {/* Premium trust indicators */}
        <div className="mt-10 space-y-6">
          <div className="text-center">
            <p className="text-sm text-zinc-400 italic">
              Strategically generated by LUVPARTNR's AI Relationship Intelligence
            </p>
          </div>

          <div className="border-t border-white/10 pt-8">
            <h2 className="text-xl font-semibold text-center mb-4">
              Understand Your Own Situation
            </h2>
            <p className="text-zinc-300 text-center mb-6">
              Gain clarity on your relationships with our premium analysis tools
            </p>
            <Link
              href="/app"
              className="w-full max-w-xs mx-auto flex items-center justify-center bg-white/10 hover:bg-white/20 transition-colors text-white font-medium py-3 px-6 rounded-lg"
            >
              Get Your Own Report →
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
